POST http://localhost:8081/api/signUp
Content-Type: application/json

{
  "login": "ldar",
  "mail": "mail",
  "password": "elvin2901"
}

###
GET http://localhost:8080/signUp
Accept: application/json

###
GET http://localhost:8080/main
Accept: application/json

###
POST http://localhost:8081/main
Content-Type: application/json

{
  "login": "ldar",
  "password": "elvin2901"
}

###



